apiVersion: v1
kind: Service
metadata:
  name: {{ include "boot2.fullname" . }}
  labels:
    {{- include "boot2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  # Fixing IP address
  loadBalancerIP: 192.168.64.95
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "boot2.selectorLabels" . | nindent 4 }}
